<?php $this->plugin('translate')->setTranslatorTextDomain('adfabmeteo');// Pour le texte ?>
    <?php
    $form = $this->form;
    $form->prepare();
    ?>
<?php echo $this->form()->openTag($form) ?>
    <?php foreach($form->get('codes') as $element):?>
        <fieldset>
            <div class="label-input">
                <?php echo $this->formHidden($element->get('id')); ?>
            </div>
            <div class="label-input">
                <?php echo $this->formLabel($element->get('code')); ?>
                <?php echo $this->formInput($element->get('code')); ?>
            </div>
            <div class="label-input">
                <?php echo $this->formLabel($element->get('description')); ?>
                <?php echo $this->formInput($element->get('description')); ?>
            </div>
            <div class="label-input">
                <?php echo $this->formHidden($element->get('isDefault')); ?>
            </div>
            <div class="label-input">
                <?php echo $this->formLabel($element->get('icon')); ?>
                <?php echo $this->formFile($element->get('icon')); ?>
                <?php if($element->get('iconURL')->getValue() != ''):?>
                    <img src="<?php echo $this->basePath($element->get('iconURL')->getValue()); ?>" />
                <?php endif;?>
            </div>
            <div class="label-input">
                <?php echo $this->formLabel($element->get('associatedCode')); ?>
                <?php echo $this->formSelect($element->get('associatedCode')); ?>
            </div>
            <hr/>
        </fieldset>
    <?php endforeach;?>


    <?php echo $this->formButton($form->get('submit')); ?>
<?php echo $this->form()->closeTag() ?>