<?php $this->plugin('translate')->setTranslatorTextDomain('adfabmeteo');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>
	<ul class="liste-buttons">
	    <li class="btn-admin"><a href="<?php echo $this->url('admin/meteo/weather-codes/import'); ?>"><?php echo $this->translate('Importer les états par défaut'); ?></a></li>
		<li class="btn-admin"><a href="<?php echo $this->url('admin/meteo/weather-codes/add'); ?>"><?php echo $this->translate('Ajouter un état du ciel'); ?></a></li>
	</ul>

	<h2>Table d'association</h2>
	<?php if ($this->appCodes) : ?>
	<h3><?php echo $this->translate('Etats du ciel personnalisés') ?></h3>
    	<table id="app_codes">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Code') ?></th>
                    <th><?php echo $this->translate('Description') ?></th>
                    <th><?php echo $this->translate('Icône') ?></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->appCodes as $code):?>
                <tr>
                    <td><?php echo $code->getCode(); ?></td>
                    <td><?php echo $code->getDescription(); ?></td>
                    <td>
                        <?php if ($code->getIconURL() != ''): ?>
                            <img src="<?php echo $this->basePath($code->getIconURL()); ?>" />
                        <?php else: ?>
                            <p>Pas d'Icone</p>
                        <?php endif;?>
                    </td>
                    <td></td>
                    <?php $editLink   = $this->url('admin/meteo/weather-codes/edit', array('codeId' => $code->getId()));?>
                    <?php $deleteLink = $this->url('admin/meteo/weather-codes/remove', array('codeId' => $code->getId()));?>
                    <td><a href='<?php echo $editLink ?>'><?php echo $this->translate('Editer'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Supprimer'); ?></a></td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    <?php endif; ?>

    <h3><?php echo $this->translate('Etats du ciel par défaut') ?></h3>
    <?php  if ($this->providerCodes) : ?>
    	<?php echo $this->form()->openTag($form) ?>
         <table id="provider_codes">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Code') ?></th>
                    <th><?php echo $this->translate('Description') ?></th>
                    <th><?php echo $this->translate('Icône') ?></th>
                    <th></th>
                    <th><?php echo $this->translate('Modifier l\'icône') ?></th>
                    <th><?php echo $this->translate('Associé à') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($form->get('codes') as $element):?>
                <tr>
                    <?php $element->get('code')->setAttribute('readonly', 'readonly'); ?>
                    <td><?php echo $this->formInput($element->get('code')); ?></td>
                    <?php $element->get('description')->setAttribute('readonly', 'readonly'); ?>
                    <td><?php echo $this->formInput($element->get('description')); ?></td>
                    <td>
                        <?php if($element->get('iconURL')->getValue() != ''): ?>
                            <img src="<?php echo $this->basePath($element->get('iconURL')->getValue()); ?>" />
                        <?php else: ?>
                            <p>Pas d'Icone</p>
                        <?php endif;?>
                    </td>
                    <td><?php echo $this->formHidden($element->get('id')); ?>
                        <?php echo $this->formHidden($element->get('isDefault')); ?></td>

                    <td><?php echo $this->formFile($element->get('icon')); ?></td>
                    <td><?php echo $this->formSelect($element->get('associatedCode')); ?></td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>

            <?php echo $this->formButton($form->get('submit')); ?>
        <?php echo $this->form()->closeTag() ?>
    <?php else : ?>
        <a href="<?php echo $this->url('admin/meteo/weather-codes/import'); ?>"><?php echo $this->translate('Importer les états par défaut'); ?></a>
    <?php endif; ?>

    <ul class="liste-buttons">
        <li class="btn-admin"><a href="<?php echo $this->url('admin/meteo/weather-codes/import'); ?>"><?php echo $this->translate('Importer les états par défaut'); ?></a></li>
		<li class="btn-admin"><a href="<?php echo $this->url('admin/meteo/weather-codes/add'); ?>"><?php echo $this->translate('Ajouter un état du ciel'); ?></a></li>
	</ul>
</div>